// One-time generator for supabase/migrations/034_shg_fu_reference_data.sql —
// the Fabula Ultima reference-data tables (classes/skills/spells/arcana/
// inventions/equipment/status effects/heroic skills/rituals & projects
// tables) that app/FU/data/**.ts currently hardcodes.
//
// Sources:
//   - app/FU/data/classes/*.ts, equipment.ts, statusEffects.ts — already a
//     verified transcription of the rulebook and already relied on by the
//     app, so they're the source of truth for everything that has a TS
//     equivalent (ids match what's already saved in players' characters).
//   - Reference/fabula_ultima_database.xlsx — the source for the two
//     genuinely new catalogs with no TS equivalent: Heroic_Skills and the
//     Rituals_*/Projects_* GM reference tables.
//
// This script only WRITES the migration file — it does not touch any
// database. Re-run it any time the source data changes; it overwrites
// 034_shg_fu_reference_data.sql wholesale. Run it with:
//   npx tsx scripts/seed-fu-reference-data.ts

import XLSX from "xlsx";
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

import { classes } from "../app/FU/data/classes";
import { weapons, armors, shields } from "../app/FU/data/equipment";
import { statusEffects } from "../app/FU/data/statusEffects";
import type { FUArmor, FUShield } from "../app/FU/data/types";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(__dirname, "..");

function slugify(name: string): string {
  return name
    .toLowerCase()
    .normalize("NFD").replace(/[̀-ͯ]/g, "")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)/g, "");
}

function str(s: string | null | undefined): string {
  if (s == null) return "null";
  return `'${s.replace(/'/g, "''")}'`;
}
function num(n: number | null | undefined): string {
  return n == null || Number.isNaN(n) ? "null" : String(n);
}
function bool(b: boolean): string {
  return b ? "true" : "false";
}
function strArray(arr: string[]): string {
  if (arr.length === 0) return "'{}'";
  return `ARRAY[${arr.map((s) => str(s)).join(", ")}]::text[]`;
}
function jsonb(value: unknown): string {
  return `'${JSON.stringify(value).replace(/'/g, "''")}'::jsonb`;
}

const lines: string[] = [];
function push(...ls: string[]) {
  lines.push(...ls);
}

push(
  "-- ═══════════════════════════════════════════════════════════════════════════",
  "-- Story Hunters Guild — Fabula Ultima reference data (classes/skills/spells/",
  "-- arcana/inventions/equipment/status effects/heroic skills/rituals & projects)",
  "-- ═══════════════════════════════════════════════════════════════════════════",
  "-- Generated by scripts/seed-fu-reference-data.ts — do not hand-edit the insert",
  "-- statements below, re-run the script instead. Run AFTER 033_shg_rol_quest_",
  "-- note_document.sql. Pure read-only reference/lookup data: shg_service (the",
  "-- app's server-side role) gets full CRUD like every other table, RLS is",
  "-- enabled with no policies so anon/authenticated can't touch it directly —",
  "-- same posture as shg_rol_guild_status (027_shg_rol_guild_status.sql).",
  "",
);

// ---------------------------------------------------------------------------
// Schema
// ---------------------------------------------------------------------------

push(
  "create table if not exists shg_fu_class (",
  "  id                  text primary key,",
  "  name                text not null,",
  "  also_known_as       text[] not null default '{}',",
  "  description         text not null,",
  "  roleplay_questions  text[] not null default '{}',",
  "  free_benefits       jsonb not null,", // FUClassBenefit[] — needs statBonus/equipGrant preserved for derivedStats.ts
  "  sort_order          int not null default 0",
  ");",
  "",
  "create table if not exists shg_fu_skill (",
  "  id           uuid primary key default gen_random_uuid(),",
  "  class_id     text not null references shg_fu_class(id) on delete cascade,",
  "  name         text not null,",
  "  max_level    int not null,", // 1 = single-take only, matching FUSkill's convention
  "  description  text not null,",
  "  sort_order   int not null default 0,",
  "  unique (class_id, name)",
  ");",
  "create index if not exists shg_fu_skill_class_idx on shg_fu_skill (class_id);",
  "",
  "create table if not exists shg_fu_spell (",
  "  id           uuid primary key default gen_random_uuid(),",
  "  class_id     text not null references shg_fu_class(id) on delete cascade,",
  "  name         text not null,",
  "  offensive    boolean not null,",
  "  mp_cost      text not null,", // kept as text: some costs are variable/formulaic
  "  target       text not null,",
  "  duration     text not null,",
  "  description  text not null,",
  "  opportunity  text,",
  "  sort_order   int not null default 0,",
  "  unique (class_id, name)",
  ");",
  "create index if not exists shg_fu_spell_class_idx on shg_fu_spell (class_id);",
  "",
  "create table if not exists shg_fu_arcanum (",
  "  id              uuid primary key default gen_random_uuid(),",
  "  class_id        text not null references shg_fu_class(id) on delete cascade,",
  "  name            text not null,",
  "  domains         text[] not null,",
  "  merge_effect    text not null,",
  "  dismiss_effect  text not null,",
  "  sort_order      int not null default 0,",
  "  unique (class_id, name)",
  ");",
  "create index if not exists shg_fu_arcanum_class_idx on shg_fu_arcanum (class_id);",
  "",
  "create table if not exists shg_fu_invention_type (",
  "  id              text primary key,",
  "  class_id        text not null references shg_fu_class(id) on delete cascade,",
  "  name            text not null,",
  "  also_known_as   text[] not null default '{}',",
  "  description     text not null,",
  "  tiers           jsonb not null,", // FUInventionTier[] — tier/name?/ipCost?/text/table?
  "  sort_order      int not null default 0",
  ");",
  "create index if not exists shg_fu_invention_type_class_idx on shg_fu_invention_type (class_id);",
  "",
  "create table if not exists shg_fu_weapon (",
  "  id          text primary key,",
  "  name        text not null,",
  "  category    text not null,",
  "  cost        int,", // null = no purchase cost (Unarmed Strike)
  "  martial     boolean not null default false,",
  "  handedness  text not null,", // 'one-handed' | 'two-handed'
  "  range_type  text not null,", // 'melee' | 'ranged'
  "  accuracy    text not null,",
  "  damage      text not null,",
  "  notes       text not null default '',",
  "  sort_order  int not null default 0",
  ");",
  "",
  "create table if not exists shg_fu_armor_shield (",
  "  id              text primary key,",
  "  name            text not null,",
  "  item_type       text not null,", // 'armor' | 'shield'
  "  cost            int not null,",
  "  martial         boolean not null default false,",
  // armor: {"fixed":N} | {"dexPlus":N} for defense, {"fixed":N} | {"insPlus":N} for magic_defense.
  // shield: {"bonus":N} for both — kept jsonb so calcDefense/calcMagicDefense's
  // discriminated-union logic (app/FU/lib/derivedStats.ts) survives the move intact.
  "  defense         jsonb not null,",
  "  magic_defense   jsonb not null,",
  "  initiative      int not null default 0,",
  "  notes           text not null default '',",
  "  sort_order      int not null default 0",
  ");",
  "",
  "create table if not exists shg_fu_inventory_item (",
  "  id          text primary key,",
  "  name        text not null,",
  "  category    text not null,",
  "  ip_cost     int not null,",
  "  effect      text not null,",
  "  sort_order  int not null default 0",
  ");",
  "",
  "create table if not exists shg_fu_status_effect (",
  "  id           text primary key,",
  "  name         text not null,",
  "  affects      text[] not null,", // FUCharacterAttributes keys this reduces
  "  description  text not null,",
  "  sort_order   int not null default 0",
  ");",
  "",
  "create table if not exists shg_fu_heroic_skill (",
  "  id           text primary key,",
  "  name         text not null,",
  "  requirement  text,", // null = open to anyone who's mastered any class
  "  description  text not null,",
  "  sort_order   int not null default 0",
  ");",
  "",
  "create table if not exists shg_fu_ritual_discipline (",
  "  id             text primary key,",
  "  name           text not null,",
  "  magic_check    text not null,",
  "  example_uses   text not null,",
  "  sort_order     int not null default 0",
  ");",
  "create table if not exists shg_fu_ritual_potency (",
  "  id              text primary key,",
  "  name            text not null,",
  "  mp_base_cost    int not null,",
  "  difficulty      int not null,",
  "  examples        text not null,",
  "  sort_order      int not null default 0",
  ");",
  "create table if not exists shg_fu_ritual_area (",
  "  id              text primary key,",
  "  name            text not null,",
  "  mp_multiplier   numeric not null,",
  "  examples        text not null,",
  "  sort_order      int not null default 0",
  ");",
  "",
  "create table if not exists shg_fu_project_potency (",
  "  id            text primary key,",
  "  name          text not null,",
  "  base_cost     int not null,",
  "  capabilities  text not null,",
  "  sort_order    int not null default 0",
  ");",
  "create table if not exists shg_fu_project_area (",
  "  id               text primary key,",
  "  name             text not null,",
  "  cost_multiplier  numeric not null,",
  "  examples         text not null,",
  "  sort_order       int not null default 0",
  ");",
  "create table if not exists shg_fu_project_uses (",
  "  id               text primary key,",
  "  name             text not null,",
  "  cost_multiplier  numeric not null,",
  "  description      text not null,",
  "  sort_order       int not null default 0",
  ");",
  "",
  "grant select, insert, update, delete on",
  "  shg_fu_class, shg_fu_skill, shg_fu_spell, shg_fu_arcanum, shg_fu_invention_type,",
  "  shg_fu_weapon, shg_fu_armor_shield, shg_fu_inventory_item, shg_fu_status_effect,",
  "  shg_fu_heroic_skill, shg_fu_ritual_discipline, shg_fu_ritual_potency, shg_fu_ritual_area,",
  "  shg_fu_project_potency, shg_fu_project_area, shg_fu_project_uses",
  "  to shg_service;",
  "",
  "alter table shg_fu_class enable row level security;",
  "alter table shg_fu_skill enable row level security;",
  "alter table shg_fu_spell enable row level security;",
  "alter table shg_fu_arcanum enable row level security;",
  "alter table shg_fu_invention_type enable row level security;",
  "alter table shg_fu_weapon enable row level security;",
  "alter table shg_fu_armor_shield enable row level security;",
  "alter table shg_fu_inventory_item enable row level security;",
  "alter table shg_fu_status_effect enable row level security;",
  "alter table shg_fu_heroic_skill enable row level security;",
  "alter table shg_fu_ritual_discipline enable row level security;",
  "alter table shg_fu_ritual_potency enable row level security;",
  "alter table shg_fu_ritual_area enable row level security;",
  "alter table shg_fu_project_potency enable row level security;",
  "alter table shg_fu_project_area enable row level security;",
  "alter table shg_fu_project_uses enable row level security;",
  "",
  "-- ─────────────────────────────────────────────────────────────────────────",
  "-- Seed data",
  "-- ─────────────────────────────────────────────────────────────────────────",
  "",
);

// ---------------------------------------------------------------------------
// Classes, Skills, Spells, Arcana, Inventions (from app/FU/data)
// ---------------------------------------------------------------------------

const classRows: string[] = [];
const skillRows: string[] = [];
const spellRows: string[] = [];
const arcanumRows: string[] = [];
const inventionRows: string[] = [];

classes.forEach((cls, classIdx) => {
  classRows.push(
    `(${str(cls.id)}, ${str(cls.name)}, ${strArray(cls.alsoKnownAs)}, ${str(cls.description)}, ${strArray(cls.roleplayQuestions)}, ${jsonb(cls.freeBenefits)}, ${classIdx})`,
  );

  cls.skills.forEach((skill, i) => {
    skillRows.push(
      `(${str(cls.id)}, ${str(skill.name)}, ${num(skill.maxLevel)}, ${str(skill.text)}, ${i})`,
    );
  });

  if (cls.subsystem?.type === "spells") {
    cls.subsystem.entries.forEach((spell, i) => {
      spellRows.push(
        `(${str(cls.id)}, ${str(spell.name)}, ${bool(spell.offensive)}, ${str(spell.mpCost)}, ${str(spell.target)}, ${str(spell.duration)}, ${str(spell.text)}, ${str(spell.opportunity ?? null)}, ${i})`,
      );
    });
  }
  if (cls.subsystem?.type === "arcana") {
    cls.subsystem.entries.forEach((arcanum, i) => {
      arcanumRows.push(
        `(${str(cls.id)}, ${str(arcanum.name)}, ${strArray(arcanum.domains)}, ${str(arcanum.mergeText)}, ${str(arcanum.dismissText)}, ${i})`,
      );
    });
  }
  if (cls.subsystem?.type === "inventions") {
    cls.subsystem.entries.forEach((invention, i) => {
      inventionRows.push(
        `(${str(`${cls.id}-${slugify(invention.name)}`)}, ${str(cls.id)}, ${str(invention.name)}, ${strArray(invention.alsoKnownAs)}, ${str(invention.description)}, ${jsonb(invention.tiers)}, ${i})`,
      );
    });
  }
});

push(
  "insert into shg_fu_class (id, name, also_known_as, description, roleplay_questions, free_benefits, sort_order) values",
  classRows.join(",\n") + "\non conflict (id) do nothing;",
  "",
  "insert into shg_fu_skill (class_id, name, max_level, description, sort_order) values",
  skillRows.join(",\n") + "\non conflict (class_id, name) do nothing;",
  "",
  "insert into shg_fu_spell (class_id, name, offensive, mp_cost, target, duration, description, opportunity, sort_order) values",
  spellRows.join(",\n") + "\non conflict (class_id, name) do nothing;",
  "",
);
if (arcanumRows.length > 0) {
  push(
    "insert into shg_fu_arcanum (class_id, name, domains, merge_effect, dismiss_effect, sort_order) values",
    arcanumRows.join(",\n") + "\non conflict (class_id, name) do nothing;",
    "",
  );
}
if (inventionRows.length > 0) {
  push(
    "insert into shg_fu_invention_type (id, class_id, name, also_known_as, description, tiers, sort_order) values",
    inventionRows.join(",\n") + "\non conflict (id) do nothing;",
    "",
  );
}

// ---------------------------------------------------------------------------
// Equipment (from app/FU/data/equipment.ts)
// ---------------------------------------------------------------------------

const weaponRows = weapons.map((w, i) =>
  `(${str(w.id)}, ${str(w.name)}, ${str(w.category)}, ${num(w.cost)}, ${bool(w.martial)}, ${str(w.handedness)}, ${str(w.range)}, ${str(w.accuracy)}, ${str(w.damage)}, ${str(w.notes)}, ${i})`,
);
push(
  "insert into shg_fu_weapon (id, name, category, cost, martial, handedness, range_type, accuracy, damage, notes, sort_order) values",
  weaponRows.join(",\n") + "\non conflict (id) do nothing;",
  "",
);

function armorDefenseJson(a: FUArmor): unknown {
  return "fixed" in a.defense ? { fixed: a.defense.fixed } : { dexPlus: a.defense.dexPlus };
}
function armorMagicDefenseJson(a: FUArmor): unknown {
  return "fixed" in a.magicDefense ? { fixed: a.magicDefense.fixed } : { insPlus: a.magicDefense.insPlus };
}

const armorRows = armors.map((a, i) =>
  `(${str(a.id)}, ${str(a.name)}, 'armor', ${num(a.cost)}, ${bool(a.martial)}, ${jsonb(armorDefenseJson(a))}, ${jsonb(armorMagicDefenseJson(a))}, ${num(a.initiative)}, ${str(a.notes)}, ${i})`,
);
const shieldRows = shields.map((s: FUShield, i) =>
  `(${str(s.id)}, ${str(s.name)}, 'shield', ${num(s.cost)}, ${bool(s.martial)}, ${jsonb({ bonus: s.defenseBonus })}, ${jsonb({ bonus: s.magicDefenseBonus })}, ${num(s.initiative)}, ${str(s.notes)}, ${i})`,
);
push(
  "insert into shg_fu_armor_shield (id, name, item_type, cost, martial, defense, magic_defense, initiative, notes, sort_order) values",
  [...armorRows, ...shieldRows].join(",\n") + "\non conflict (id) do nothing;",
  "",
);

const statusEffectRows = statusEffects.map((e, i) =>
  `(${str(e.id)}, ${str(e.name)}, ${strArray(e.affects)}, ${str(e.description)}, ${i})`,
);
push(
  "insert into shg_fu_status_effect (id, name, affects, description, sort_order) values",
  statusEffectRows.join(",\n") + "\non conflict (id) do nothing;",
  "",
);

// ---------------------------------------------------------------------------
// Inventory items, Heroic Skills, Rituals & Projects tables (from the xlsx —
// no TS equivalent exists for any of these yet).
// ---------------------------------------------------------------------------

const wb = XLSX.readFile(path.join(repoRoot, "Reference", "fabula_ultima_database.xlsx"));
function sheet<T>(name: string): T[] {
  return XLSX.utils.sheet_to_json<T>(wb.Sheets[name], { defval: null });
}

interface InventoryItemRow { item_name: string; category: string; ip_cost: number; effect: string }
const inventoryItemRows = sheet<InventoryItemRow>("Inventory_Items").map((row, i) =>
  `(${str(slugify(row.item_name))}, ${str(row.item_name)}, ${str(row.category)}, ${num(row.ip_cost)}, ${str(row.effect)}, ${i})`,
);
push(
  "insert into shg_fu_inventory_item (id, name, category, ip_cost, effect, sort_order) values",
  inventoryItemRows.join(",\n") + "\non conflict (id) do nothing;",
  "",
);

interface HeroicSkillRow { skill_name: string; requirement: string | null; description: string }
const heroicSkillRows = sheet<HeroicSkillRow>("Heroic_Skills").map((row, i) =>
  `(${str(slugify(row.skill_name))}, ${str(row.skill_name)}, ${str(row.requirement)}, ${str(row.description)}, ${i})`,
);
push(
  "insert into shg_fu_heroic_skill (id, name, requirement, description, sort_order) values",
  heroicSkillRows.join(",\n") + "\non conflict (id) do nothing;",
  "",
);

interface RitualDisciplineRow { discipline_name: string; magic_check: string; example_uses: string }
const ritualDisciplineRows = sheet<RitualDisciplineRow>("Rituals_Disciplines").map((row, i) =>
  `(${str(slugify(row.discipline_name))}, ${str(row.discipline_name)}, ${str(row.magic_check)}, ${str(row.example_uses)}, ${i})`,
);
push(
  "insert into shg_fu_ritual_discipline (id, name, magic_check, example_uses, sort_order) values",
  ritualDisciplineRows.join(",\n") + "\non conflict (id) do nothing;",
  "",
);

interface RitualPotencyRow { potency_name: string; mp_base_cost: number; difficulty_level: number; examples: string }
const ritualPotencyRows = sheet<RitualPotencyRow>("Rituals_Potency").map((row, i) =>
  `(${str(slugify(row.potency_name))}, ${str(row.potency_name)}, ${num(row.mp_base_cost)}, ${num(row.difficulty_level)}, ${str(row.examples)}, ${i})`,
);
push(
  "insert into shg_fu_ritual_potency (id, name, mp_base_cost, difficulty, examples, sort_order) values",
  ritualPotencyRows.join(",\n") + "\non conflict (id) do nothing;",
  "",
);

interface RitualAreaRow { area_name: string; mp_multiplier: number; examples: string }
const ritualAreaRows = sheet<RitualAreaRow>("Rituals_Area").map((row, i) =>
  `(${str(slugify(row.area_name))}, ${str(row.area_name)}, ${num(row.mp_multiplier)}, ${str(row.examples)}, ${i})`,
);
push(
  "insert into shg_fu_ritual_area (id, name, mp_multiplier, examples, sort_order) values",
  ritualAreaRows.join(",\n") + "\non conflict (id) do nothing;",
  "",
);

interface ProjectPotencyRow { potency_name: string; base_cost: string; capabilities: string }
const projectPotencyRows = sheet<ProjectPotencyRow>("Projects_Potency").map((row, i) =>
  `(${str(slugify(row.potency_name))}, ${str(row.potency_name)}, ${num(parseInt(row.base_cost, 10))}, ${str(row.capabilities)}, ${i})`,
);
push(
  "insert into shg_fu_project_potency (id, name, base_cost, capabilities, sort_order) values",
  projectPotencyRows.join(",\n") + "\non conflict (id) do nothing;",
  "",
);

interface ProjectAreaRow { area_name: string; cost_multiplier: number; examples: string }
const projectAreaRows = sheet<ProjectAreaRow>("Projects_Area").map((row, i) =>
  `(${str(slugify(row.area_name))}, ${str(row.area_name)}, ${num(row.cost_multiplier)}, ${str(row.examples)}, ${i})`,
);
push(
  "insert into shg_fu_project_area (id, name, cost_multiplier, examples, sort_order) values",
  projectAreaRows.join(",\n") + "\non conflict (id) do nothing;",
  "",
);

interface ProjectUsesRow { uses_name: string; cost_multiplier: number; description: string }
const projectUsesRows = sheet<ProjectUsesRow>("Projects_Uses").map((row, i) =>
  `(${str(slugify(row.uses_name))}, ${str(row.uses_name)}, ${num(row.cost_multiplier)}, ${str(row.description)}, ${i})`,
);
push(
  "insert into shg_fu_project_uses (id, name, cost_multiplier, description, sort_order) values",
  projectUsesRows.join(",\n") + "\non conflict (id) do nothing;",
  "",
);

const outPath = path.join(repoRoot, "supabase", "migrations", "034_shg_fu_reference_data.sql");
fs.writeFileSync(outPath, lines.join("\n") + "\n");

console.log(`Wrote ${outPath}`);
console.log(
  `Rows: ${classRows.length} classes, ${skillRows.length} skills, ${spellRows.length} spells, ` +
  `${arcanumRows.length} arcana, ${inventionRows.length} invention types, ${weaponRows.length} weapons, ` +
  `${armorRows.length + shieldRows.length} armor/shields, ${statusEffectRows.length} status effects, ` +
  `${inventoryItemRows.length} inventory items, ${heroicSkillRows.length} heroic skills, ` +
  `${ritualDisciplineRows.length} ritual disciplines, ${ritualPotencyRows.length} ritual potencies, ` +
  `${ritualAreaRows.length} ritual areas, ${projectPotencyRows.length} project potencies, ` +
  `${projectAreaRows.length} project areas, ${projectUsesRows.length} project uses.`,
);
